dict-i18n:
  loader-order:
    - declared
    - yml
    - properties
    - redis
  max-recursion-depth: 10
  default-lang: zh
  loader:
    declared:
      enabled: false
    file:
      enabled: true
      location-patterns:
        #        - http://127.0.0.1:8081/dict_zh-CN.yml
        - dict_i18n/dict_*.yml
    redis:
      enabled: false

  starter:
    endpoint:
      dict-items:
        enabled: true
    enhancer:
      enabled: true
    check:
      unique-dict-name:
        enabled: true
    scan-packages:
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
logging:
  level:
    cn.silwings: debug
