dict-i18n:
  loader-order:
    - sql
    - redis
    - file
    - declared
  max-nesting-depth: 10
  default-lang: zh
  loader:
    declared:
      enabled: false
    file:
      enabled: true
    redis:
      enabled: false
      key-prefix: 'dict_i18n_demo'
      preload:
        enabled: false
        fail-fast: true
        preload-mode: full
    sql:
      enabled: false
      schema:
        enabled: true
      preload:
        enabled: false
        preload-mode: full
      cache:
        enabled: false

  starter:
    endpoint:
      enabled: true
      dict-items:
        enabled: true
      dict-names:
        enabled: true
    enhancer:
      enabled: true
    check:
      unique-dict-name:
        enabled: true
    scan-packages:
spring:
  profiles:
    active: '@spring.profiles.active@'
  redis:
    host: localhost
    port: 6379
    database: 0
logging:
  level:
    cn.silwings: debug
