dict-i18n:
  loader-order:
    - declared
    - file
    - redis
  max-recursion-depth: 10
  default-lang: zh
  loader:
    declared:
      enabled: true
    file:
      enabled: true
      location-patterns:
    redis:
      enabled: true
      key-prefix: 'dict_i18n_demo:'
      preload:
        enabled: true
        fail-fast: true
    sql:
      schema:
        enabled: true

  starter:
    endpoint:
      dict-items:
        enabled: true
    enhancer:
      enabled: true
    check:
      unique-dict-name:
        enabled: true
    scan-packages:
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  #  datasource:
  #    url:  jdbc:mysql://localhost:3306/dict_i18n_demo?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=true&allowPublicKeyRetrieval=true
  #    username: root
  #    password: root
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
logging:
  level:
    cn.silwings: debug
